/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ZOMBIE
 */
public class frmPasienBayi extends javax.swing.JDialog {
DefaultTableModel tabmode;
private frmPasienIbu pasienibu=new frmPasienIbu(null, false);
    public frmPasienBayi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"No Rm Bayi","Nama Ibu","Tgl Lahir","Jam","Umur","Proses Lahir","Jens Kelamin","Berat Badan","Pnjang Badan","Lingkar Kepala","Tgl Daftar","Keterangan","Anak ke-"};
        setLocationRelativeTo(null);
        tabmode=new DefaultTableModel(judul,0);
        tabelPasienBayi.setModel(tabmode);
        muncul();
        pasienibu.getData().addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (pasienibu.getData().getRowCount()!=-1){
                    txtrmIbu.setText(pasienibu.getMode().getValueAt(
                            pasienibu.getData().getSelectedRow(),0).toString());
                    txtCariIbu.setText(pasienibu.getMode().getValueAt(
                            pasienibu.getData().getSelectedRow(),1).toString());
                }
            }
            @Override
            public void mousePressed(MouseEvent e) {}
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtrmBayi = new javax.swing.JTextField();
        txtrmIbu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBB = new javax.swing.JTextField();
        txtPjgBadan = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();
        tbKeluar = new javax.swing.JButton();
        tbCetak = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPasienBayi = new javax.swing.JTable();
        txtProsesLahir = new javax.swing.JTextField();
        cmbJk = new javax.swing.JComboBox();
        txtLingkarKepala = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAnakKe = new javax.swing.JTextField();
        tbbaru = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TxtCari = new javax.swing.JTextField();
        txtCariIbu = new javax.swing.JTextField();
        TbCari = new javax.swing.JButton();
        TglLhr = new uz.ncipro.calendar.JDateTimePicker();
        TglDaftar = new uz.ncipro.calendar.JDateTimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PASIEN BAYI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("No.rm_Bayi :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 62, -1, -1));
        getContentPane().add(txtrmBayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 59, 176, -1));
        getContentPane().add(txtrmIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 98, 73, -1));

        jLabel3.setText("No.rm_Ibu :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setText("Tgl.Lahir :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setText("Jam :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        getContentPane().add(txtJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 176, -1));

        jLabel6.setText("Umur :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));
        getContentPane().add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, -1));

        jLabel7.setText("Proses Lahir :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel13.setText("Keterangan :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jLabel12.setText("Tanggal Daftar :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel11.setText("Lingkar Kepala :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jLabel10.setText("Panjang Badan :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel9.setText("Berat Badan :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel8.setText("Jenis Kelamin :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));
        getContentPane().add(txtBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 140, -1));
        getContentPane().add(txtPjgBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 176, -1));
        getContentPane().add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 176, -1));

        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        tbCetak.setText("Cetak");
        tbCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCetakActionPerformed(evt);
            }
        });
        getContentPane().add(tbCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        tbEdit.setText("Edit");
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });
        getContentPane().add(tbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 63, -1));

        tbSimpan.setText("Simpan");
        tbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tbSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        tabelPasienBayi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPasienBayi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienBayiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPasienBayi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 834, 230));
        getContentPane().add(txtProsesLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 176, -1));

        cmbJk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        getContentPane().add(cmbJk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 140, -1));
        getContentPane().add(txtLingkarKepala, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 176, -1));

        jLabel14.setText("Anak Ke- :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        getContentPane().add(txtAnakKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, -1));

        tbbaru.setText("Baru");
        tbbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbaruActionPerformed(evt);
            }
        });
        getContentPane().add(tbbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel15.setText("Keyword :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(TxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 143, -1));
        getContentPane().add(txtCariIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 98, 135, -1));

        TbCari.setText("...");
        TbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbCariActionPerformed(evt);
            }
        });
        getContentPane().add(TbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 97, -1, -1));

        TglLhr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "26/12/2014" }));
        TglLhr.setDisplayFormat("dd/MM/yyyy");
        getContentPane().add(TglLhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 175, -1));

        TglDaftar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "26/12/2014" }));
        TglDaftar.setDisplayFormat("dd/MM/yyyy");
        getContentPane().add(TglDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 175, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbaruActionPerformed
        txtrmBayi.setText("");
        txtAnakKe.setText("");
        txtBB.setText("");
        txtJam.setText("");
        txtKeterangan.setText("");
        txtLingkarKepala.setText("");
        txtPjgBadan.setText("");
        txtProsesLahir.setText("");
        cmbJk.setSelectedIndex(0);
        txtUmur.setText("");
        txtrmIbu.setText("");
}//GEN-LAST:event_tbbaruActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int row=tabmode.getRowCount();
            for (int i=0;i<row;i++){
                tabmode.removeRow(0);
            }
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
            ResultSet rs=koneksi.createStatement().executeQuery("select pasien_bayi.no_rm_bayi,pasien_ibu.nm_pasien,pasien_bayi.tgl_lahir,pasien_bayi.jam,pasien_bayi.umur,pasien_bayi.proses_lahir,pasien_bayi.j_kel,pasien_bayi.berat_badan, "+
                    "pasien_bayi.panjang_badan,pasien_bayi.lingkar_kepala,pasien_bayi.tgl_daftar,pasien_bayi.keterangan,pasien_bayi.anakke from pasien_bayi inner join pasien_ibu on pasien_bayi.no_rm_ibu=pasien_ibu.no_rm_ibu where pasien_bayi.no_rm_bayi like '%"+
                    TxtCari.getText()+"%' or pasien_ibu.no_rm_ibu like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.tgl_lahir like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.jam like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.umur like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.proses_lahir like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.j_kel like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.berat_badan like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.panjang_badan like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.lingkar_kepala like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.tgl_daftar like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.keterangan like '%"+
                    TxtCari.getText()+"%' or pasien_bayi.anakke like '%"+
                    TxtCari.getText()+"%'");
            while (rs.next()){
                String[] data={rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)};
                tabmode.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        try {
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
            koneksi.createStatement().execute("delete from pasien_bayi where no_rm_bayi= '" +
                    txtrmBayi.getText()+"'");
            muncul();
            JOptionPane.showMessageDialog(rootPane, "Data Pasien Bayi berhasil Di Hapus");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tabelPasienBayiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienBayiMouseClicked
        int i=tabelPasienBayi.getSelectedRow();
        if (i>-1){
        txtrmBayi.setText(tabmode.getValueAt(i, 0). toString());
        txtCariIbu.setText(tabmode.getValueAt(i, 1). toString());
        //TglLhr.setSelectedItem(tabmode.getValueAt(i, 2). toString());
        txtJam.setText(tabmode.getValueAt(i, 3). toString());
        txtUmur.setText(tabmode.getValueAt(i, 4). toString());
        txtProsesLahir.setText(tabmode.getValueAt(i, 5). toString());
        cmbJk.setSelectedItem(tabmode.getValueAt(i, 6). toString());
        txtBB.setText(tabmode.getValueAt(i, 7). toString());
        txtPjgBadan.setText(tabmode.getValueAt(i, 8). toString());
        txtLingkarKepala.setText(tabmode.getValueAt(i, 9). toString());
        //TglDaftar.setSelectedItem(tabmode.getValueAt(i, 10). toString());
        txtKeterangan.setText(tabmode.getValueAt(i, 11). toString());
        txtAnakKe.setText(tabmode.getValueAt(i, 12). toString());
        }
        try {
            TglLhr.setDisplayFormat("yyyy-MM-dd");
            TglDaftar.setDisplayFormat("yyyy-MM-dd");
            Date dtpa = new SimpleDateFormat("yyyy-MM-dd").parse(tabmode.getValueAt(i,2).toString());
            Date dtpa1 = new SimpleDateFormat("yyyy-MM-dd").parse(tabmode.getValueAt(i,10).toString());
            TglLhr.setDate(dtpa);
            TglDaftar.setDate(dtpa1);
            TglLhr.setDisplayFormat("dd/MM/yyyy");
            TglDaftar.setDisplayFormat("dd/MM/yyyy");
        } catch (ParseException ex) {
            Logger.getLogger(frmDokter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelPasienBayiMouseClicked

    private void tbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpanActionPerformed
        try {
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
            TglLhr.setDisplayFormat("yyyy-MM-dd");
            TglDaftar.setDisplayFormat("yyyy-MM-dd");
            koneksi.createStatement().executeUpdate("insert into pasien_bayi values"+
                        "('"+txtrmBayi.getText()+
                        "','"+txtrmIbu.getText()+
                        "','"+TglLhr.getSelectedItem()+
                        "','"+txtJam.getText()+
                        "','"+txtUmur.getText()+
                        "','"+txtProsesLahir.getText()+
                        "','"+cmbJk.getSelectedItem()+
                        "','"+txtBB.getText()+
                        "','"+txtPjgBadan.getText()+
                        "','"+txtLingkarKepala.getText()+
                        "','"+TglDaftar.getSelectedItem()+
                        "','"+txtKeterangan.getText()+
                        "','"+txtAnakKe.getText()+"')");
            TglLhr.setDisplayFormat("dd/MM/yyyy");
            TglDaftar.setDisplayFormat("dd/MM/yyyy");
            muncul();
            JOptionPane.showMessageDialog(rootPane, "Data Pasien Bayi berhasil Di simpan");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            
    }//GEN-LAST:event_tbSimpanActionPerformed

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        try {
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
            TglLhr.setDisplayFormat("yyyy-MM-dd");
            TglDaftar.setDisplayFormat("yyyy-MM-dd");
            Statement rs=koneksi.createStatement();
            rs.execute("update pasien_bayi inner join pasien_ibu on pasien_bayi.no_rm_ibu=pasien_bayi.no_rm_ibu set pasien_bayi.no_rm_ibu= '" +
                txtrmIbu.getText() + "' ,pasien_bayi.tgl_lahir='" +
                TglLhr.getSelectedItem() + "' ,pasien_bayi.jam='" +
                txtJam.getText() + "' ,pasien_bayi.umur='" +
                txtUmur.getText() + "' ,pasien_bayi.proses_lahir='" +
                txtProsesLahir.getText() + "' ,pasien_bayi.j_kel='" +
                cmbJk.getSelectedItem() + "' ,pasien_bayi.berat_badan='" +
                txtBB.getText() + "' ,pasien_bayi.panjang_badan='" +
                txtPjgBadan.getText() + "' ,pasien_bayi.lingkar_kepala='" +
                txtLingkarKepala.getText() + "' ,pasien_bayi.tgl_daftar='" +
                TglDaftar.getSelectedItem() + "' ,pasien_bayi.keterangan='" +
                txtKeterangan.getText() + "' ,pasien_bayi.anakke='" +
                txtAnakKe.getText() + "' where pasien_bayi.no_rm_bayi= '" +
                txtrmBayi.getText() + "'");
            TglLhr.setDisplayFormat("dd/MM/yyyy");
            TglDaftar.setDisplayFormat("dd/MM/yyyy");
            muncul();
            JOptionPane.showMessageDialog(rootPane, "Data Pasien Bayi berhasil Di edit");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            
    }//GEN-LAST:event_tbEditActionPerformed

    private void TbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbCariActionPerformed
        pasienibu.setLocationRelativeTo(null);
        pasienibu.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "Pilih Data Pasien Ibu");
    }//GEN-LAST:event_TbCariActionPerformed

    private void tbCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCetakActionPerformed
        try {
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
                JasperReport Jrpt=JasperCompileManager.compileReport("./report/ReportPasBayi.jrxml");
                JasperPrint jsp=JasperFillManager.fillReport(Jrpt, new HashMap<Object, Object>(),koneksi);
                JasperViewer view=new JasperViewer(jsp,false);
                view.setFitPageZoomRatio();
                view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(frmPasienBayi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmPasienBayi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPasienBayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPasienBayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPasienBayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPasienBayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPasienBayi dialog = new frmPasienBayi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TbCari;
    private uz.ncipro.calendar.JDateTimePicker TglDaftar;
    private uz.ncipro.calendar.JDateTimePicker TglLhr;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JComboBox cmbJk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPasienBayi;
    private javax.swing.JButton tbCetak;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbSimpan;
    private javax.swing.JButton tbbaru;
    private javax.swing.JTextField txtAnakKe;
    private javax.swing.JTextField txtBB;
    private javax.swing.JTextField txtCariIbu;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtLingkarKepala;
    private javax.swing.JTextField txtPjgBadan;
    private javax.swing.JTextField txtProsesLahir;
    private javax.swing.JTextField txtUmur;
    private javax.swing.JTextField txtrmBayi;
    private javax.swing.JTextField txtrmIbu;
    // End of variables declaration//GEN-END:variables


    public JTable getdata(){
        return tabelPasienBayi;
    }
    public DefaultTableModel getMode(){
        return tabmode;
    }

    private void muncul() {
        int row=tabmode.getRowCount();
        for (int i=0;i<row;i++){
            tabmode.removeRow(0);
        }
        try {
            Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/medica","root","");
            ResultSet rs=koneksi.createStatement().executeQuery("select pasien_bayi.no_rm_bayi,pasien_ibu.nm_pasien,pasien_bayi.tgl_lahir,pasien_bayi.jam,pasien_bayi.umur,pasien_bayi.proses_lahir,pasien_bayi.j_kel,pasien_bayi.berat_badan, "+
                    "pasien_bayi.panjang_badan,pasien_bayi.lingkar_kepala,pasien_bayi.tgl_daftar,pasien_bayi.keterangan,pasien_bayi.anakke "+
                    "from pasien_bayi inner join pasien_ibu on pasien_bayi.no_rm_ibu=pasien_ibu.no_rm_ibu");
            while(rs.next()){
            String[] data={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)};
            tabmode.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
}

